### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by metmajer** [jptomo/ansible-connection-nsenter#1]
Hi @jptomo - great project!!

Can you provide a sample inventory, playbook and ansible.cfg as a starting point please? Thanks!

**Comment by tomoh1r** [comment]
Thanks your comment.

Updated README.rst Quick Start Section.

Please refer to it.

best regarts.

**Comment by metmajer** [comment]
Hey @jptomo. The documentation is much better now, thanks!
